# Matrices

## Matrices with Numpy

In [1]:
import numpy as np

In [3]:
X = np.array([[42, 11], [7, 100], [30, 3]])
X

array([[ 42,  11],
       [  7, 100],
       [ 30,   3]])

In [4]:
X.shape

(3, 2)

In [5]:
# number of elements in matrix
X.size

6

In [8]:
# all rows, only first column of X
X[:, 0]

array([42,  7, 30])

In [9]:
# all columns, only middle column of X
X[1,:]

array([  7, 100])

In [10]:
X[0:2, 0:2]

array([[ 42,  11],
       [  7, 100]])

## Matrices in PyTorch

In [11]:
import torch

In [12]:
X_torch = torch.tensor([[42, 11], [7, 100], [30, 3]])
X_torch

tensor([[ 42,  11],
        [  7, 100],
        [ 30,   3]])

In [13]:
X_torch.shape

torch.Size([3, 2])

In [14]:
X_torch[1, :]

tensor([  7, 100])

## Matrices in TensorFlow

In [16]:
import tensorflow as tf

In [17]:
X_tf = tf.Variable([[42, 11], [7, 100], [30, 3]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[ 42,  11],
       [  7, 100],
       [ 30,   3]], dtype=int32)>

In [18]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [19]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [20]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([  7, 100], dtype=int32)>