# Norms

In [1]:
import numpy as np

In [2]:
x = np.array([42, 11, 7])

## L2 Norm

$||x||_{2}=\sqrt{\sum{x_{i}^{2}}}$

Measures simple (Euclidean) distance from origin.

In [6]:
x

array([42, 11,  7])

In [7]:
(42**2 + 11**2 + 7**2)**(1/2)

43.977266854592045

In [8]:
np.linalg.norm(x)

43.977266854592045

## L1 Norm

$||x||_{1}=\sum{|x_{i}|}$

Varies linearly at all locations whether near or far from origin. Used when difference b/w zero and non-zero key.

In [9]:
x

array([42, 11,  7])

In [10]:
np.abs(42) + np.abs(11) + np.abs(7)

60

## Squared L2 Norm

$||x||_{2}^{2}=\sum{x_{i}^{2}}$

Computationally cheaper than L2 Norm, but downside is that it grows slowly near the origin, so do not use if distinguishing between zero and near-zero is important.

In [13]:
x

array([42, 11,  7])

In [14]:
(42**2 + 11**2 + 7**2)

1934

In [15]:
np.dot(x, x)

1934

## Max Norm

$L_{\infty}=max_{i}|x_{i}|$

Returns absolute value of largest magnitude element.

In [16]:
x

array([42, 11,  7])

In [18]:
np.max([np.abs(42), np.abs(11), np.abs(7)])

42