# Vectors

In [1]:
import numpy as np

## Vectors with Numpy

In [2]:
x = np.array([42, 11, 7])
x

array([42, 11,  7])

In [3]:
len(x)

3

In [4]:
x.shape

(3,)

In [5]:
type(x)

numpy.ndarray

In [7]:
x[0]

42

In [8]:
type(x[0])

numpy.int64

In [6]:
x_float = np.array([42, 11, 7], dtype=np.float16)
type(x_float)

numpy.ndarray

In [9]:
x_float[0]

42.0

In [10]:
type(x_float[0])

numpy.float16

## Vector Transposition

In [11]:
# Transposition on 1-D vector (array) does not do anything
x_t = x.T
x_t

array([42, 11,  7])

In [12]:
x_t.shape

(3,)

In [13]:
# Using matrix brackets does allow for transposition to take place
y = np.array([[42, 11, 7]])
y

array([[42, 11,  7]])

In [14]:
y.shape

(1, 3)

In [15]:
y_t = y.T
y_t

array([[42],
       [11],
       [ 7]])

In [16]:
y_t.shape

(3, 1)

In [17]:
# Transposing a transposed vector brings it back to its original form
y_t.T.shape

(1, 3)

## Zero Vectors

In [20]:
z = np.zeros(3)
z

array([0., 0., 0.])

## Vectors with PyTorch

In [21]:
import torch

In [22]:
x_torch = torch.tensor([42, 11, 7])
x_torch

tensor([42, 11,  7])

## Vectors with TensorFlow

In [23]:
import tensorflow as tf

In [24]:
x_tf = tf.Variable([42, 11, 7])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([42, 11,  7], dtype=int32)>