# Frobenius Norm

$ ||X||_{F}=\sqrt{\sum_{i=1}\sum_{j=1}X_{i,j}^2}$

## Numpy

In [1]:
import numpy as np

In [3]:
X = np.array([[42, 7], [11, 9]])
X

array([[42,  7],
       [11,  9]])

In [4]:
(42**2 + 7**2 + 11**2 + 9**2)**(1/2)

44.88875137492688

In [5]:
np.linalg.norm(X) # same as L2 norm for vectors

44.88875137492688

## PyTorch

In [6]:
import torch

In [9]:
X_torch = torch.tensor([[42, 7], [11, 9]], dtype=torch.float16) # must be floats for Frobenius norm
X_torch

tensor([[42.,  7.],
        [11.,  9.]], dtype=torch.float16)

In [10]:
torch.norm(X_torch)

tensor(44.8750, dtype=torch.float16)

## TensorFlow

In [11]:
import tensorflow as tf

In [12]:
X_tf = tf.Variable([[42,7], [11,9]], dtype=tf.float16) # must be floats for Frobenius norm
X_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float16, numpy=
array([[42.,  7.],
       [11.,  9.]], dtype=float16)>

In [13]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float16, numpy=44.88>