# Matrix by Vector Multiplication

Number of columns of first matrix must be equal to number of rows of second one.

## Numpy

In [1]:
import numpy as np

In [2]:
A = np.array([[3,4], [5,6], [7,8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [3]:
b = np.array([1,2])
b

array([1, 2])

In [4]:
np.dot(A,b) # even though technically dot product only b/w vectors

array([11, 17, 23])

## PyTorch

In [5]:
import torch

In [6]:
A_torch = torch.tensor([[3,4], [5,6], [7,8]])
A_torch

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [7]:
b_torch = torch.tensor([1,2])
b_torch

tensor([1, 2])

In [8]:
torch.matmul(A_torch, b_torch)

tensor([11, 17, 23])

## TensorFlow

In [9]:
import tensorflow as tf

In [10]:
A_tf = tf.Variable([[3,4], [5,6], [7,8]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [11]:
b_tf = tf.Variable([1,2])
b_tf

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [12]:
tf.linalg.matvec(A_tf, b_tf) # in TensorFlow required to specify if Matrix by Vector via matvec

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23], dtype=int32)>