# Eigendecomposition

$A=V\Lambda V^{-1}$

- $V$ is the concatenation of all Eigenvectors of $A$
- $\Lambda$ is $diag(\lambda)$ where $\lambda$ is the vector of Eigenvalues
- usually the $\lambda$'s are arranged in descending order, so that the first eigenvalue with its associated eigenvector may be primary characteristic of matrix $A$

## Numpy
### Eigendecomposition with asymmetric matrix

$A=V\Lambda V^{-1}$


In [1]:
import numpy as np

In [2]:
A = np.array([[4,2], [-5,-3]])
A

array([[ 4,  2],
       [-5, -3]])

In [3]:
lambdas, V = np.linalg.eig(A)

In [4]:
V

array([[ 0.70710678, -0.37139068],
       [-0.70710678,  0.92847669]])

In [5]:
lambdas

array([ 2., -1.])

In [6]:
V_inv = np.linalg.inv(V)
V_inv

array([[2.3570226 , 0.94280904],
       [1.79505494, 1.79505494]])

In [7]:
Lambda = np.diag(lambdas)
Lambda

array([[ 2.,  0.],
       [ 0., -1.]])

In [8]:
np.dot(V, np.dot(Lambda, V_inv)) # confirm Eigendecomposition

array([[ 4.,  2.],
       [-5., -3.]])

## Numpy
### Eigendecomposition with symmetric matrix

$A=Q\Lambda Q^{T}$

- $Q$ analogous to $V$ except its an orthogonal matrix, hence $Q^{-1}=Q^{T}$
- orthogonal means $Q^{-1}Q^{T}=I$
- useful for ML because cheap to compute transpose as opposed to inverse


In [9]:
A = np.array([[2,1], [1,2]])
A

array([[2, 1],
       [1, 2]])

In [10]:
lambdas, Q = np.linalg.eig(A)

In [11]:
Q

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [12]:
lambdas

array([3., 1.])

In [13]:
Lambda = np.diag(lambdas)
Lambda

array([[3., 0.],
       [0., 1.]])

In [14]:
np.dot(Q, np.dot(Lambda, Q.T)) # confirm Eigendecomposition characteristic

array([[2., 1.],
       [1., 2.]])

In [15]:
np.dot(Q.T, Q) # confirm that Q is orthogonal

array([[1.00000000e+00, 2.23711432e-17],
       [2.23711432e-17, 1.00000000e+00]])

In [16]:
np.dot(Q, Q.T) # confirm that Q is orthogonal

array([[ 1.00000000e+00, -2.23711432e-17],
       [-2.23711432e-17,  1.00000000e+00]])

## PyTorch
### Eigendecomposition with asymmetric matrix

$A=V\Lambda V^{-1}$


In [17]:
import torch

In [18]:
A_torch = torch.tensor([[25,2,-5], [3,-2,1], [5,7,4.]]) # must be floats
A_torch

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [19]:
lambdas_torch, V_torch = torch.linalg.eig(A_torch)

In [20]:
V_torch = V_torch.float()
V_torch

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at  /pytorch/aten/src/ATen/native/Copy.cpp:240.)
  """Entry point for launching an IPython kernel.


tensor([[ 0.9511, -0.2386,  0.1626],
        [ 0.1218, -0.1924, -0.7705],
        [ 0.2837, -0.9519,  0.6163]])

In [21]:
V_torch_inv = torch.linalg.inv(V_torch)
V_torch_inv

tensor([[ 1.1356,  0.0102, -0.2868],
        [ 0.3914, -0.7198, -1.0032],
        [ 0.0817, -1.1164,  0.2052]])

In [22]:
Lambda_torch = torch.diag(lambdas_torch.float())
Lambda_torch

tensor([[23.7644,  0.0000,  0.0000],
        [ 0.0000,  6.6684,  0.0000],
        [ 0.0000,  0.0000, -3.4328]])

In [23]:
torch.matmul(V_torch, torch.matmul(Lambda_torch, V_torch_inv)) # confirm Eigendecomposition characteristic

tensor([[25.0000,  2.0000, -5.0000],
        [ 3.0000, -2.0000,  1.0000],
        [ 5.0000,  7.0000,  4.0000]])

## TensorFlow
### Eigendecomposition with symmetric matrix

$A=Q\Lambda Q^{T}$

In [24]:
import tensorflow as tf

In [25]:
A_tf = tf.Variable([[25,2,-5], [2,-2,1], [-5,1,4.]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[25.,  2., -5.],
       [ 2., -2.,  1.],
       [-5.,  1.,  4.]], dtype=float32)>

In [26]:
lambdas_tf, Q_tf = tf.linalg.eig(A_tf)

In [27]:
Q_tf = tf.cast(Q_tf, dtype=tf.float32)
Q_tf

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.11323708, -0.19428189,  0.974388  ],
       [-0.9650548 , -0.25476408,  0.06135537],
       [ 0.23631889, -0.9472855 , -0.21634144]], dtype=float32)>

In [28]:
Q_tf_T = tf.transpose(Q_tf)
Q_tf_T

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.11323708, -0.9650548 ,  0.23631889],
       [-0.19428189, -0.25476408, -0.9472855 ],
       [ 0.974388  ,  0.06135537, -0.21634144]], dtype=float32)>

In [29]:
lambdas_tf = tf.cast(lambdas_tf, dtype=tf.float32)
lambdas_tf

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-2.479551 ,  3.2434747, 26.236074 ], dtype=float32)>

In [30]:
Lambda_tf = tf.linalg.diag(lambdas_tf)
Lambda_tf

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-2.479551 ,  0.       ,  0.       ],
       [ 0.       ,  3.2434747,  0.       ],
       [ 0.       ,  0.       , 26.236074 ]], dtype=float32)>

In [31]:
tf.matmul(Q_tf, tf.matmul(Lambda_tf, Q_tf_T)) # confirm Eigendecomposition characteristic

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[25.       ,  2.0000002, -5.       ],
       [ 2.0000002, -1.9999999,  0.9999998],
       [-5.       ,  0.9999998,  4.       ]], dtype=float32)>