# Basic Tensor Arithmetic

Adding and multiplying with scalars applies the operation to all tensor elements and the shape is kept.

## Numpy

In [1]:
import numpy as np

In [2]:
X = np.array([[42, 11], [7, 100], [30, 3]])
X

array([[ 42,  11],
       [  7, 100],
       [ 30,   3]])

In [3]:
X*2

array([[ 84,  22],
       [ 14, 200],
       [ 60,   6]])

In [4]:
X+2

array([[ 44,  13],
       [  9, 102],
       [ 32,   5]])

In [5]:
X*2+2

array([[ 86,  24],
       [ 16, 202],
       [ 62,   8]])

## PyTorch

In [6]:
import torch

In [7]:
X_torch = torch.tensor([[42, 11], [7, 100], [30, 3]])
X_torch

tensor([[ 42,  11],
        [  7, 100],
        [ 30,   3]])

In [8]:
X_torch*2

tensor([[ 84,  22],
        [ 14, 200],
        [ 60,   6]])

In [9]:
torch.mul(X_torch, 2)

tensor([[ 84,  22],
        [ 14, 200],
        [ 60,   6]])

In [10]:
X_torch+2

tensor([[ 44,  13],
        [  9, 102],
        [ 32,   5]])

In [11]:
torch.add(X_torch, 2)

tensor([[ 44,  13],
        [  9, 102],
        [ 32,   5]])

In [13]:
X_torch*2+2

tensor([[ 86,  24],
        [ 16, 202],
        [ 62,   8]])

In [15]:
torch.add(torch.mul(X_torch, 2), 2)

tensor([[ 86,  24],
        [ 16, 202],
        [ 62,   8]])

## TensorFlow

In [16]:
import tensorflow as tf

In [17]:
X_tf = tf.Variable([[42, 11], [7, 100], [30, 3]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[ 42,  11],
       [  7, 100],
       [ 30,   3]], dtype=int32)>

In [18]:
X_tf*2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 84,  22],
       [ 14, 200],
       [ 60,   6]], dtype=int32)>

In [19]:
tf.multiply(X_tf, 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 84,  22],
       [ 14, 200],
       [ 60,   6]], dtype=int32)>

In [20]:
X_tf+2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 44,  13],
       [  9, 102],
       [ 32,   5]], dtype=int32)>

In [21]:
tf.add(X_tf, 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 44,  13],
       [  9, 102],
       [ 32,   5]], dtype=int32)>

In [22]:
X_tf*2+2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 86,  24],
       [ 16, 202],
       [ 62,   8]], dtype=int32)>

In [23]:
tf.add(tf.multiply(X_tf, 2), 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 86,  24],
       [ 16, 202],
       [ 62,   8]], dtype=int32)>