# Hadamard Product of Tensors (NOT Matrix-Multiplication)

$A \odot X$

If two tensors are of the same shape, arithmetic operations are often executed element-wise.

## Numpy

In [1]:
import numpy as np

In [4]:
X = np.array([[42, 11], [7, 100], [30, 3]])
X

array([[ 42,  11],
       [  7, 100],
       [ 30,   3]])

In [5]:
A = X + 2
A

array([[ 44,  13],
       [  9, 102],
       [ 32,   5]])

In [6]:
A + X

array([[ 86,  24],
       [ 16, 202],
       [ 62,   8]])

In [7]:
A * X

array([[ 1848,   143],
       [   63, 10200],
       [  960,    15]])

## PyTorch

In [8]:
import torch

In [9]:
X_torch = torch.tensor([[42, 11], [7, 100], [30, 3]])
X_torch

tensor([[ 42,  11],
        [  7, 100],
        [ 30,   3]])

In [10]:
A_torch = X_torch + 2
A_torch

tensor([[ 44,  13],
        [  9, 102],
        [ 32,   5]])

In [11]:
A_torch + X_torch

tensor([[ 86,  24],
        [ 16, 202],
        [ 62,   8]])

In [12]:
A_torch * X_torch

tensor([[ 1848,   143],
        [   63, 10200],
        [  960,    15]])

## TensorFlow

In [13]:
import tensorflow as tf

In [14]:
X_tf = tf.Variable([[42, 11], [7, 100], [30, 3]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[ 42,  11],
       [  7, 100],
       [ 30,   3]], dtype=int32)>

In [15]:
A_tf = X_tf + 2
A_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 44,  13],
       [  9, 102],
       [ 32,   5]], dtype=int32)>

In [16]:
A_tf + X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 86,  24],
       [ 16, 202],
       [ 62,   8]], dtype=int32)>

In [17]:
A_tf * X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1848,   143],
       [   63, 10200],
       [  960,    15]], dtype=int32)>