# Tensor Reduction

Calculating the sum, maximum, minimum, mean, product, etc. across all tensor elements. Here only sums.

## Numpy

In [1]:
import numpy as np

In [2]:
X = np.array([[42, 11], [7, 100], [30, 3]])
X

array([[ 42,  11],
       [  7, 100],
       [ 30,   3]])

In [3]:
X.sum()

193

In [4]:
# axis = 0 executes operations across all rows i.e. down each column
X.sum(axis=0)

array([ 79, 114])

In [5]:
# axis = 1 executes operations across all columns i.e. along each row
X.sum(axis=1)

array([ 53, 107,  33])

## PyTorch

In [6]:
import torch

In [7]:
X_torch = torch.tensor([[42, 11], [7, 100], [30, 3]])
X_torch

tensor([[ 42,  11],
        [  7, 100],
        [ 30,   3]])

In [8]:
torch.sum(X_torch)

tensor(193)

In [9]:
torch.sum(X_torch, 0) # across all rows i.e. down each column

tensor([ 79, 114])

In [10]:
torch.sum(X_torch, 1) # across all columns i.e. along each row

tensor([ 53, 107,  33])

## TensorFlow

In [11]:
import tensorflow as tf

In [12]:
X_tf = tf.Variable([[42, 11], [7, 100], [30, 3]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[ 42,  11],
       [  7, 100],
       [ 30,   3]], dtype=int32)>

In [13]:
tf.reduce_sum(X_tf, 0) # across all rows i.e. down each column

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 79, 114], dtype=int32)>

In [14]:
tf.reduce_sum(X_tf, 1) # across all columns i.e. along each row

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 53, 107,  33], dtype=int32)>