# Tensor Transposition

## Numpy

In [2]:
import numpy as np

In [3]:
X = np.array([[42, 11], [7, 100], [30, 3]])
X

array([[ 42,  11],
       [  7, 100],
       [ 30,   3]])

In [4]:
X.T

array([[ 42,   7,  30],
       [ 11, 100,   3]])

## PyTorch

In [5]:
import torch

In [6]:
X_torch = torch.Tensor([[42, 11], [7, 100], [30, 3]])
X_torch

tensor([[ 42.,  11.],
        [  7., 100.],
        [ 30.,   3.]])

In [7]:
X_torch.T

tensor([[ 42.,   7.,  30.],
        [ 11., 100.,   3.]])

## TensorFlow

In [8]:
import tensorflow as tf

In [9]:
X_tf = tf.Variable([[42, 11], [7, 100], [30, 3]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[ 42,  11],
       [  7, 100],
       [ 30,   3]], dtype=int32)>

In [10]:
tf.transpose(X_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 42,   7,  30],
       [ 11, 100,   3]], dtype=int32)>