# Tensor Reduction

Calculating the sum, maximum, minimum, mean, product, etc. across all tensor elements. Here only sums.

## Numpy

In [15]:
import numpy as np

In [16]:
X = np.array([[42, 11], [7, 100], [30, 3]])
X

array([[ 42,  11],
       [  7, 100],
       [ 30,   3]])

In [17]:
X.sum()

193

In [18]:
# axis = 0 executes operations across all rows i.e. down each column
X.sum(axis=0)

array([ 79, 114])

In [19]:
# axis = 1 executes operations across all columns i.e. along each row
X.sum(axis=1)

array([ 53, 107,  33])

## PyTorch

In [20]:
import torch

In [21]:
X_torch = torch.tensor([[42, 11], [7, 100], [30, 3]])
X_torch

tensor([[ 42,  11],
        [  7, 100],
        [ 30,   3]])

In [22]:
torch.sum(X_torch)

tensor(193)

In [23]:
torch.sum(X_torch, 0) # across all rows i.e. down each column

tensor([ 79, 114])

In [24]:
torch.sum(X_torch, 1) # across all columns i.e. along each row

tensor([ 53, 107,  33])

## TensorFlow

In [25]:
import tensorflow as tf

In [26]:
X_tf = tf.Variable([[42, 11], [7, 100], [30, 3]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[ 42,  11],
       [  7, 100],
       [ 30,   3]], dtype=int32)>

In [27]:
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=193>

In [28]:
tf.reduce_sum(X_tf, 0) # across all rows i.e. down each column

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 79, 114], dtype=int32)>

In [29]:
tf.reduce_sum(X_tf, 1) # across all columns i.e. along each row

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 53, 107,  33], dtype=int32)>