# Vector Dot Product

Given two vectors <b>x</b> and <b>y</b>, which <u>must</u> have the same length <i>n</i>, their dot product becomes:

$x\cdot y=\sum_{i=1}^{n}x_{i}y_{i}$

which can also be denoted as:

$x^Ty$

$\langle{x,y}\rangle$

This type of tensor operation is executed at every artificial neuron in deep neural networks.

## Numpy

In [1]:
import numpy as np

In [2]:
x = np.array([42, 11, 7])
x

array([42, 11,  7])

In [3]:
y = np.array([23, 55, 1])
y

array([23, 55,  1])

In [4]:
42*23 + 11*55 + 7*1

1578

In [5]:
np.dot(x,y)

1578

## PyTorch

In [6]:
import torch

In [7]:
x_torch = torch.tensor([42, 11, 7], dtype=torch.float16)
x_torch

tensor([42., 11.,  7.], dtype=torch.float16)

In [8]:
y_torch = torch.tensor([23, 55, 1], dtype=torch.float16)
y_torch

tensor([23., 55.,  1.], dtype=torch.float16)

In [9]:
np.dot(x_torch, y_torch) # do not need to be floats here

1578.0

In [10]:
torch.dot(x_torch, y_torch) # must be floats here

tensor(1578., dtype=torch.float16)

## TensorFlow

In [11]:
import tensorflow as tf

In [12]:
x_tf = tf.Variable([42, 11, 7])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([42, 11,  7], dtype=int32)>

In [13]:
y_tf = tf.Variable([23, 55, 1])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([23, 55,  1], dtype=int32)>

In [14]:
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=1578>