# Singular Value Decomposition (SVD)

$A=UDV^{T}$

- $A$ real-valued $m \times n$ matrix
- $U$ orthogonal $m \times m$ matrix; columns are left-singular vectors of $A$
- $V$ orthogonal $n \times n$ matrix; columns are right-singular vectors of $A$ (hence $V^T$ rows are right-singular vectors of $A$)
- $D$ diagonal $m \times n$ matrix; diagonal elements are the singular values of $A$

SVD and Eigendecomposition are closely related to each other:
- Left-singular vectors of $A$ (columns of $U$) = Eigenvectors $v$ of $AA^T$
- Right-singular vectors of $A$ (rows of $V^T$) = Eigenvectors $v$ of $A^{T}A$
- Non-zero singular values of $A$ = square roots of Eigenvectors $v$ of $AA^T$ = square roots of Eigenvectors $v$ of $A^{T}A$

# Numpy

In [1]:
import numpy as np

In [2]:
A = np.array([[-1,2], [3,-2], [5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [3]:
A.shape # (m x n) = (3 x 2)

(3, 2)

In [4]:
U, d, VT = np.linalg.svd(A)

In [5]:
U 

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [6]:
U.shape # (m x m) = (3 x 3)

(3, 3)

In [7]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [8]:
VT.shape # (n x n) = (2 x 2)

(2, 2)

In [9]:
d # is a vector and must be converted via np.diag(d) to get diagonal matrix

array([8.66918448, 4.10429538])

In [10]:
np.diag(d)

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

In [11]:
np.diag(d).shape # is square 2x2 here, so must be converted to (m x n) = (3 x 2)

(2, 2)

In [12]:
D = np.concatenate((np.diag(d), [[0,0]]), axis=0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [13]:
D.shape # (m x n) = (3 x 2)

(3, 2)

In [14]:
# Confirm SVD equation 
np.dot(U, np.dot(D, VT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])

 ## PyTorch

In [15]:
import torch

In [16]:
A_torch = torch.tensor([[25,2,-5], [3,-2,1], [5,7,4.]])
A_torch

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [17]:
A_torch.shape # (m x n) = (3 x 3)

torch.Size([3, 3])

In [18]:
U_torch, d_torch, VT_torch = torch.linalg.svd(A_torch)

In [19]:
U_torch

tensor([[-0.9757,  0.1823,  0.1214],
        [-0.0975,  0.1350, -0.9860],
        [-0.1961, -0.9739, -0.1140]])

In [20]:
U_torch.shape # (m x m) = (3 x 3)

torch.Size([3, 3])

In [21]:
VT_torch

tensor([[-0.9810, -0.1196,  0.1528],
        [ 0.0113, -0.8211, -0.5706],
        [-0.1937,  0.5581, -0.8069]])

In [22]:
VT_torch.shape # (n x n) = (3 x 3)

torch.Size([3, 3])

In [23]:
d_torch # diagonal must be (m x n) = (3 x 3)

tensor([26.1632,  8.1875,  2.5395])

In [24]:
D_torch = torch.diag(d_torch)
D_torch

tensor([[26.1632,  0.0000,  0.0000],
        [ 0.0000,  8.1875,  0.0000],
        [ 0.0000,  0.0000,  2.5395]])

In [25]:
D_torch.shape # (m x n) = (3 x 3)

torch.Size([3, 3])

In [26]:
torch.matmul(U_torch, torch.matmul(D_torch, VT_torch)) # check SVD equation fulfilled

tensor([[25.0000,  2.0000, -5.0000],
        [ 3.0000, -2.0000,  1.0000],
        [ 5.0000,  7.0000,  4.0000]])