# Identity Matrices

- symmetric matrix i.e. #rows=#columns and transpose=original
- every element along main diagonal is 1
- all other elements are 0
- notation is $I_{n}$ where n is the height, which equals the width since symmetric
- a matching matrix multiplied by the identity matrix yields the same matrix

## Numpy

In [1]:
import numpy as np

In [2]:
I = np.array([[1,0,0], [0,1,0], [0,0,1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [3]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.dot(I,A)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.dot(A,I)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## PyTorch

In [6]:
import torch

In [7]:
I_torch = torch.tensor([[1,0,0], [0,1,0], [0,0,1]])
I_torch

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [8]:
A_torch = torch.from_numpy(A)
A_torch

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
torch.matmul(I_torch, A_torch)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## TensorFlow

In [10]:
import tensorflow as tf

In [11]:
I_tf = tf.Variable([[1,0,0], [0,1,0], [0,0,1]])
I_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)>

In [12]:
A_tf = tf.convert_to_tensor(A, dtype=tf.int32)
A_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [13]:
tf.matmul(I_tf, A_tf)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>