# Matrix Inversion

can only be calculated if:
- matrix is NOT singular i.e. all columns must be linearly independent
- matrix is square i.e. $n_{rows}=n_{columns}$ so that $n_{equations}=n_{dimensions}$ so that vector span equals vector range...otherwise overdetermined ($n_{rows}>n_{columns}$) or underdetermined ($n_{rows}<n_{columns}$)

## Numpy

In [1]:
import numpy as np

In [2]:
X = np.array([[4,2], [-5,-3]])
X

array([[ 4,  2],
       [-5, -3]])

In [3]:
X_inv = np.linalg.inv(X)
X_inv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [4]:
np.dot(X,X_inv)

array([[ 1.0000000e+00, -4.4408921e-16],
       [ 4.4408921e-16,  1.0000000e+00]])

In [5]:
np.dot(X_inv, X)

array([[1.00000000e+00, 3.33066907e-16],
       [0.00000000e+00, 1.00000000e+00]])

### Numpy: Solving system of equations with inverse matrix

In [6]:
y = np.array([4, -7])
y

array([ 4, -7])

In [7]:
w = np.dot(X_inv, y)
w

array([-1.,  4.])

In [8]:
np.dot(X, w)

array([ 4., -7.])

## PyTorch

In [9]:
import torch

In [10]:
X_torch = torch.tensor([[4,2], [-5,-3]], dtype=torch.float) # must be float for inversion
X_torch

tensor([[ 4.,  2.],
        [-5., -3.]])

In [11]:
X_torch_inv = torch.inverse(X_torch)
X_torch_inv

tensor([[ 1.5000,  1.0000],
        [-2.5000, -2.0000]])

In [12]:
torch.matmul(X_torch, X_torch_inv)

tensor([[ 1.0000e+00,  0.0000e+00],
        [-4.7684e-07,  1.0000e+00]])

### PyTorch: Solving system of equations with inverse matrix

In [13]:
y_torch = torch.tensor([4, -7], dtype=torch.float)
y_torch

tensor([ 4., -7.])

In [14]:
w_torch = torch.matmul(X_torch_inv, y_torch)
w_torch

tensor([-1.,  4.])

In [15]:
torch.matmul(X_torch,w_torch)

tensor([ 4., -7.])

## TensorFlow

In [16]:
import tensorflow as tf

In [17]:
X_tf = tf.Variable([[4,2], [-5,-3]], dtype=tf.float32)
X_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 4.,  2.],
       [-5., -3.]], dtype=float32)>

In [18]:
X_tf_inv = tf.linalg.inv(X_tf)
X_tf_inv

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.4999999 ,  0.99999994],
       [-2.4999998 , -1.9999999 ]], dtype=float32)>

In [19]:
tf.matmul(X_tf, X_tf_inv)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.0000000e+00,  0.0000000e+00],
       [-4.7683716e-07,  1.0000000e+00]], dtype=float32)>

### TensorFlow: Solving system of equations with inverse matrix

In [20]:
y_tf = tf.Variable([4, -7], dtype=tf.float32)
y_tf

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([ 4., -7.], dtype=float32)>

In [21]:
w_tf = tf.linalg.matvec(X_tf_inv, y_tf)
w_tf

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.,  4.], dtype=float32)>

In [22]:
tf.linalg.matvec(X_tf, w_tf)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 4., -7.], dtype=float32)>

## Numpy example with no inversion possible

In [23]:
X = np.array([[-4,1], [-8,2]])
X

array([[-4,  1],
       [-8,  2]])

In [24]:
X_inv = np.linalg.inv(X) # will lead to "Singular Matrix" error since not linearly independent

LinAlgError: ignored