# Matrix by Matrix Multiplication

Number of columns of first matrix must be equal to number of rows of second matrix.

## Numpy

In [1]:
import numpy as np

In [2]:
A = np.array([[3,4], [5,6], [7,8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [3]:
B = np.array([[1,9], [2,0]])
B

array([[1, 9],
       [2, 0]])

In [4]:
np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

In [5]:
np.dot(B, A) # will throw error because dimensions are off

ValueError: ignored

## PyTorch

In [6]:
import torch

In [8]:
A_torch = torch.tensor([[3,4], [5,6], [7,8]])
A_torch

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [9]:
B_torch = torch.tensor([[1,9], [2,0]])
B_torch

tensor([[1, 9],
        [2, 0]])

In [10]:
# also possible to convert Numpy matrix into PyTorch matrix
B_torch = torch.from_numpy(B)
B_torch

tensor([[1, 9],
        [2, 0]])

In [11]:
torch.matmul(A_torch, B_torch)

tensor([[11, 27],
        [17, 45],
        [23, 63]])

## TensorFlow

In [12]:
import tensorflow as tf

In [13]:
A_tf = tf.Variable([[3,4], [5,6], [7,8]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [14]:
B_tf = tf.Variable([[1,9], [2,0]])
B_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 9],
       [2, 0]], dtype=int32)>

In [15]:
# also possible to convert Numpy matrix into TensorFlow matrix
B_tf = tf.convert_to_tensor(B, dtype=tf.int32)
B_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [2, 0]], dtype=int32)>

In [16]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]], dtype=int32)>