# Orthogonal Matrices

- all rows and columns orthonormal (i.e. at 90° and with L2-Norm of 1)
- hence, $A^{T}A=AA^{T}=I$
- and $A^{T}=A^{-1}I=A^{-1}$
- computationally efficient to use to produce inverse

## Numpy: orthogonality of Identity Matrix

- all rows and columns orthonormal (i.e. at 90° and with L2-Norm of 1)
- hence, $A^{T}A=AA^{T}=I$

In [1]:
import numpy as np

In [2]:
I = np.array([[1,0,0], [0,1,0], [0,0,1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [3]:
column_1 = I[:,0]
column_1

array([1, 0, 0])

In [4]:
column_2 = I[:,1]
column_2

array([0, 1, 0])

In [5]:
column_3 = I[:,2]
column_3

array([0, 0, 1])

In [6]:
np.dot(column_1, column_2) # dot product must be 0

0

In [7]:
np.dot(column_1, column_3) # dot product must be 0

0

In [8]:
np.dot(column_2, column_3) # dot product must be 0

0

In [9]:
np.linalg.norm(column_1) # L2 norm must be 1

1.0

In [10]:
np.linalg.norm(column_2) # L2 norm must be 1

1.0

In [11]:
np.linalg.norm(column_3) # L2 norm must be 1

1.0

In [12]:
I_T = I.T
I_T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
np.dot(I_T, I) # transpose multiplied with original must be identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## PyTorch: orthogonality of generic matrix

All rows and columns orthonormal (i.e. at 90° and with L2-Norm of 1)

In [14]:
import torch

In [15]:
A_torch = torch.tensor([[2/3, -2/3, 1/3], [1/3, 2/3, 2/3], [2/3, 1/3, -2/3]])
A_torch

tensor([[ 0.6667, -0.6667,  0.3333],
        [ 0.3333,  0.6667,  0.6667],
        [ 0.6667,  0.3333, -0.6667]])

Check for orthonormal columns

In [16]:
A_torch_col1 = A_torch[:,0]
A_torch_col1

tensor([0.6667, 0.3333, 0.6667])

In [17]:
A_torch_col2 = A_torch[:,1]
A_torch_col2

tensor([-0.6667,  0.6667,  0.3333])

In [18]:
A_torch_col3 = A_torch[:,2]
A_torch_col3

tensor([ 0.3333,  0.6667, -0.6667])

In [19]:
torch.matmul(A_torch_col1, A_torch_col2) # dot product must be 0

tensor(0.)

In [20]:
torch.matmul(A_torch_col1, A_torch_col3) # dot product must be 0

tensor(0.)

In [21]:
torch.matmul(A_torch_col2, A_torch_col3) # dot product must be 0

tensor(0.)

In [22]:
torch.norm(A_torch_col1) # L2 norm must be 1

tensor(1.)

In [23]:
torch.norm(A_torch_col2) # L2 norm must be 1

tensor(1.)

In [24]:
torch.norm(A_torch_col3) # L2 norm must be 1

tensor(1.)

Check for orthonormal rows

In [25]:
A_torch_T = A_torch.T
A_torch_T

tensor([[ 0.6667,  0.3333,  0.6667],
        [-0.6667,  0.6667,  0.3333],
        [ 0.3333,  0.6667, -0.6667]])

In [26]:
A_torch_T == A_torch # if not equal then must check if rows are also orthonormal

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

In [27]:
A_torch_row1 = A_torch[0,:]
A_torch_row1

tensor([ 0.6667, -0.6667,  0.3333])

In [28]:
A_torch_row2 = A_torch[1,:]
A_torch_row2

tensor([0.3333, 0.6667, 0.6667])

In [29]:
A_torch_row3 = A_torch[2,:]
A_torch_row3

tensor([ 0.6667,  0.3333, -0.6667])

In [30]:
torch.matmul(A_torch_row1, A_torch_row2) # dot product must be 0

tensor(0.)

In [31]:
torch.matmul(A_torch_row1, A_torch_row3) # dot product must be 0

tensor(0.)

In [32]:
torch.matmul(A_torch_row2, A_torch_row3) # dot product must be 0

tensor(0.)

In [33]:
torch.norm(A_torch_row1) # L2 norm must be 1

tensor(1.)

In [34]:
torch.norm(A_torch_row2) # L2 norm must be 1

tensor(1.)

In [35]:
torch.norm(A_torch_row3) # L2 norm must be 1

tensor(1.)

## TensorFlow: use same matrix with transpose to show orthogonality

- $A^{T}A=AA^{T}=I$
- $A^{T}=A^{-1}I=A^{-1}$


In [36]:
import tensorflow as tf

In [37]:
A_tf = tf.Variable([[2/3, -2/3, 1/3], [1/3, 2/3, 2/3], [2/3, 1/3, -2/3]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.6666667 , -0.6666667 ,  0.33333334],
       [ 0.33333334,  0.6666667 ,  0.6666667 ],
       [ 0.6666667 ,  0.33333334, -0.6666667 ]], dtype=float32)>

In [38]:
A_tf_T = tf.transpose(A_tf)
A_tf_T

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.6666667 ,  0.33333334,  0.6666667 ],
       [-0.6666667 ,  0.6666667 ,  0.33333334],
       [ 0.33333334,  0.6666667 , -0.6666667 ]], dtype=float32)>

In [39]:
tf.matmul(A_tf, A_tf_T) # original multiplied with transpose must be identity

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000001e+00, -3.3113690e-09,  3.3113690e-09],
       [-3.3113690e-09,  1.0000000e+00,  6.6227379e-09],
       [ 3.3113690e-09,  6.6227379e-09,  1.0000000e+00]], dtype=float32)>

In [40]:
tf.linalg.inv(A_tf) # inverse must be equal to transpose

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.6666666 ,  0.33333325,  0.66666675],
       [-0.6666667 ,  0.6666666 ,  0.33333334],
       [ 0.33333334,  0.6666667 , -0.6666667 ]], dtype=float32)>