# Symmetric Matrices

- have as many rows as columns
- transpose of matrix is equal to original matrix

## Numpy

In [1]:
import numpy as np

In [2]:
X_sym = np.array([[0,1,2], [1,7,8], [2,8,9]])
X_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [3]:
X_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [4]:
X_sym == X_sym.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## PyTorch

In [5]:
import torch

In [6]:
X_sym_torch = torch.tensor([[0,1,2], [1,7,8], [2,8,9]])
X_sym_torch

tensor([[0, 1, 2],
        [1, 7, 8],
        [2, 8, 9]])

In [7]:
X_sym_torch == X_sym_torch.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## TensorFlow

In [8]:
import tensorflow as tf

In [9]:
X_sym_tf = tf.Variable([[0,1,2], [1,7,8], [2,8,9]])
X_sym_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]], dtype=int32)>

In [10]:
X_sym_tf == tf.transpose(X_sym_tf)

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>